---
title: "PhoneUsers"
author: "Group D"
date: "2024-04-10"
output: html_document
---

```{r include=FALSE}
# Clear workspace, install library & import data
library("caret")
library("Metrics")
library("corrplot")
set.seed(1234)
```

```{r include=FALSE}
rm(list = ls())
train <- read.csv("phone_train.csv", header=TRUE)
test <- read.csv("phone_validation.csv", header=TRUE)

train$sex <- as.factor(train$sex)
train$payment.method <- as.factor(train$payment.method)
train$activation.zone <- as.factor(train$activation.zone)
train$activation.channel <- as.factor(ifelse(train$activation.channel==5, 1, 0)) #Merge
train$tariff.plan <- as.factor(ifelse(train$tariff.plan <= 6, 1, train$tariff.plan)) #Merge
train$vas1 <- as.factor(train$vas1)
train$vas2 <- as.factor(train$vas2)

# test$sex <- as.factor(test$sex)
# test$payment.method <- as.factor(test$payment.method)
# test$activation.zone <- as.factor(ifelse(test$activation.zone == 0, 1, test$activation.zone))
# test$activation.channel <- as.factor(ifelse(test$activation.channel==5, 1, 0)) #Merge
# test$tariff.plan <- as.factor(ifelse(test$tariff.plan <= 6, 1, test$tariff.plan)) #Merge
# test$vas1 <- as.factor(test$vas1)
# test$vas2 <- as.factor(test$vas2)
```

```{r}
plot(train$sex)
plot(train$payment.method)
plot(train$activation.zone)
summary(train$activation.zone)

plot(train$activation.channel)
summary(train$activation.zone)
summary(test$activation.zone)

plot(train[,89:98])

summary(train)
```

```{r}
plotdata <- function (column, title, ylim){
  plot(1, mean(train[,paste("q01", column, sep = "")]), pch=16, col=1, xlab = "Month", ylab = "Value", main = title, xlim = c(1, 9), ylim = ylim)
  for (i in 2:9) {
    points(i, mean(train[, paste("q0", i, column, sep="")]), pch=16, col=i)
  }
}
```



```{r}
plotdata(".out.ch.peak", "mean total monthly number of outgoing calls\nat times when the tariff is highest", c(50, 110))
#plotdata(".out.dur.peak", "mean total monthly duration of outgoing calls\nat times when the tariff is highest", c(5000, 13000))
#plotdata(".out.val.peak", "mean total monthly value of outgoing calls\nat times when the tariff is highest", c(25, 60))

plotdata(".out.ch.offpeak", "mean total monthly number of outgoing calls during off-peak hours", c(0, 10))
#plotdata(".out.dur.offpeak", "mean total monthly duration of outgoing calls during off-peak hours", c(300, 900))
#plotdata(".out.val.offpeak", "mean total monthly value of outgoing calls during off-peak hours", c(0, 4))

plotdata(".in.ch.tot", "mean total monthly number of incoming calls", c(50, 100))
#plotdata(".in.dur.tot", "mean total monthly duration of incoming calls", c(4000, 9000))

plotdata(".ch.sms", "mean total monthly number of SMS sent", c(0, 5))
plotdata(".ch.cc", "mean total monthly number of calls to the Customer Service Centre", c(0, 1))
```

```{r}
for (i in 0:8) {
  index = i * 10 + 9
  corrplot(cor(train[,index:(index+2)]), method = "number")
  #corrplot(cor(train[,(index+3):(index+5)]), method = "number")
  #corrplot(cor(train[,(index+6):(index+7)]), method = "number")
}
```

```{r}
# train$q01.out.dur.peak <- NULL
# train$q01.out.val.peak <- NULL
# train$q02.out.dur.peak <- NULL
# train$q02.out.val.peak <- NULL
# train$q03.out.dur.peak <- NULL
# train$q03.out.val.peak <- NULL
# train$q04.out.dur.peak <- NULL
# train$q04.out.val.peak <- NULL
# train$q05.out.dur.peak <- NULL
# train$q05.out.val.peak <- NULL
# train$q06.out.dur.peak <- NULL
# train$q06.out.val.peak <- NULL
# train$q07.out.dur.peak <- NULL
# train$q07.out.val.peak <- NULL
# train$q08.out.dur.peak <- NULL
# train$q08.out.val.peak <- NULL
# train$q09.out.dur.peak <- NULL
# train$q09.out.val.peak <- NULL
# 
# train$q01.out.dur.offpeak <- NULL
# train$q01.out.val.offpeak <- NULL
# train$q02.out.dur.offpeak <- NULL
# train$q02.out.val.offpeak <- NULL
# train$q03.out.dur.offpeak <- NULL
# train$q03.out.val.offpeak <- NULL
# train$q04.out.dur.offpeak <- NULL
# train$q04.out.val.offpeak <- NULL
# train$q05.out.dur.offpeak <- NULL
# train$q05.out.val.offpeak <- NULL
# train$q06.out.dur.offpeak <- NULL
# train$q06.out.val.offpeak <- NULL
# train$q07.out.dur.offpeak <- NULL
# train$q07.out.val.offpeak <- NULL
# train$q08.out.dur.offpeak <- NULL
# train$q08.out.val.offpeak <- NULL
# train$q09.out.dur.offpeak <- NULL
# train$q09.out.val.offpeak <- NULL
# 
# train$q01.in.dur.tot <- NULL
# train$q02.in.dur.tot <- NULL
# train$q03.in.dur.tot <- NULL
# train$q04.in.dur.tot <- NULL
# train$q05.in.dur.tot <- NULL
# train$q06.in.dur.tot <- NULL
# train$q07.in.dur.tot <- NULL
# train$q08.in.dur.tot <- NULL
# train$q09.in.dur.tot <- NULL

```

```{r}
baseModel <- lm(y ~ 1, data = train)
FwStepSel <- step(baseModel, direction = "forward", scope = list(lower = baseModel, upper = lm(y ~ ., data = train)), trace = 0)

#Based on the previous step results:
fit = lm(formula = FwStepSel$call$formula, data = train)
summary(fit)
#yhat = predict(fit, newdata=test)
```

```{r}
fullModel <- lm(y ~ ., data = train)
BwStepSel <- step(fullModel, direction="backward", trace = 0)


#Based on the previous step results:
fit = lm(formula = BwStepSel$call$formula, data = train)
summary(fit)
yhat = predict(fit, newdata=test)
```

```{r}
library(randomForest)
# Train a Random Forest classification model
rf_model <- randomForest(y ~ ., data = train, mtry = 30, importance = TRUE)
summary(rf_model)
# Extract feature importance
importance(rf_model)
# Visualize feature importance
varImpPlot(rf_model)
yhat <- predict(rf_model, newdata=test)
```

Random forest with mtry search (DO NOT RUN, TOO LONG)

```{r}
# Define a grid of mtry values to search over
# tuneGrid <- expand.grid(mtry = seq(1, ncol(train) - 1, by = 1))

# Set up cross-validation control
#rForestCtrl <- trainControl(method = "cv", number = 5, search = "grid")

# Train the model with the tuning grid
# rForestFit <- train(y ~ ., data = train, method = "rf", preProcess = c("center", "scale"), tuneGrid = tuneGrid, allowParallel = TRUE)

# Get the importance of each feature and plot it
# importance <- importance(rForestFit$finalModel)
# varImpPlot(rForestFit$finalModel)

# Predict the quality of the test set
# yhat = predict(rForestFit, newdata = test)

# Get the final mtry value
# rForestFit$finalModel$mtry

```


```{r}
#fit <- lm(y ~ . , data=train)
#summary(fit)
#yhat <- predict(fit, newdata=test)
write.table(file="mySubmission.txt", pmax(0, yhat), row.names = FALSE,col.names = FALSE)
```
