---
title: "PhoneUsers"
author: "Group D"
date: "2024-04-22"
output: html_document
---


```{r include=FALSE}
# Clear workspace, install library & import data
library(corrplot)
library("caret")
library("Metrics")
library(MASS)
library(ggplot2)
library(gridExtra)
set.seed(1234)
```

## Importing Dataset (Task #1)
```{r}
rm(list = ls())
df <- read.csv("./dataset/rice_train.csv")
trainIndex <- createDataPartition(df$Class, 
								  times=1, 
								  p = .8, 
								  list = FALSE)
train <- df[trainIndex, ]
test <- df[-trainIndex, ]
head(train)
summary(train)

```


## Data exploration (Task #2)

### Boxplots
```{r}
boxplot(train$Area ~ train$Class, xlab="Class", ylab = "Area")
boxplot(train$Perimeter ~ train$Class, xlab="Class", ylab = "Perimeter")
boxplot(train$Major_Axis_Length ~ train$Class, xlab="Class", ylab = "MajorAxisLength")
boxplot(train$Minor_Axis_Length ~ train$Class, xlab="Class", ylab = "MinorAxisLength")
boxplot(train$Eccentricity ~ train$Class, xlab="Class", ylab = "Eccentricity")
boxplot(train$Convex_Area ~ train$Class, xlab="Class", ylab = "ConvexArea")
boxplot(train$Extent ~ train$Class, xlab="Class", ylab = "EquivDiameter")

plot(train[,])
```

### Scatterplots
```{r}
plot(train$Area, train$Perimeter, type='p', col=ifelse(train$Class == 1, "darkred", "lightblue"), xlab = "Area", ylab = "Perimeter")
plot(train$Convex_Area, train$Area, type='p', col=ifelse(train$Class == 1, "darkred", "lightblue"), xlab = "ConvexArea", ylab = "Area")
```

```{r}
# Compute correlation matrix
correlation_matrix <- cor(train)

# Visualize correlation matrix
corrplot(correlation_matrix, method = "color")
```


## Performing LDA (Task #4)
```{r}
resLda <- lda(formula = Class ~ ., data = train)
resLda
```

## Performing QDA (Task #5)
```{r}
resLda <- qda(formula = Class ~ ., data = train)
resLda
```


##KNN
```{r}
library(caret)
library(class)

#preproc

preProcValues <- preProcess(train, method = c("center", "scale"))
trainKNN <- predict(preProcValues, train)
testKNN <- predict(preProcValues, test)

knnModel <- train(
		     Class ~ ., 
		     data = trainKNN, 
	            method = "knn", 
		     trControl = trainControl(method = "cv"), 
		     tuneGrid = data.frame(k = seq(1,81, by=5))
		    )

best_model<- knn3(
                  Class ~ .,
                  data = trainKNN,
                  k = knnModel$bestTune$k
                 )

predictions <- predict(best_model, testKNN, type = "class")
# Calculate confusion matrix
cm <- confusionMatrix(predictions, testKNN$Class)
cm


```